export const types = {
    ADD_CATEGORIES: "ADD_CATEGORIES",
    ADD_PRODUCTS: "ADD_PRODUCTS",
    FILL_BASKET: "FILL_BASKET",
    REMOVE_BASKET: "REMOVE_BASKET",
    REMOVE_PRODUCT: "REMOVE_PRODUCT",
    SELECT_CATEGORIES: "SELECT_CATEGORIES"
};
